# Generated by Django 6.0.5 on 2026-05-26 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_number', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
