# Generated by Django 6.0.5 on 2026-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default="ST. JOSEPH'S HARDWARES", max_length=200)),
                ('address', models.TextField(default='New Extension, Madikeri - 571 201')),
                ('mobile', models.CharField(default='9902237176', max_length=20)),
                ('gstin', models.CharField(default='29ANWPD0218LIZO', max_length=20)),
                ('bank_account_no', models.CharField(blank=True, default='348601010036056', max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, default='UBIN0900079', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='Union Bank of India, Madikeri', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=50)),
            ],
            options={
                'verbose_name': 'Shop Settings',
            },
        ),
    ]
